library(tidyverse)
library(knitr)
library(markdown)
library(rmarkdown)
library(here)

here::i_am("scripts/temperature_qaqc_report_automator.R")

# Location of CSV files. Currently, this is recursive so files may be in sub directory structure (e.g. BN, BS, SN, etc)
filePath <- here("data_input/temperature")

# Location of the "key".  This is generated by tidbit_key_from_survey123.R and is a table relating serial number to sensor locations.
# Currently, this needs to have the following columns in this order: Serial, Basin, Station, SensorMedium, StationID.  
stationKeyLoc <- here("metadata/temperature_logger_serial_lookup.csv")

# Unique basin names found in the key.  
basinNames <- read_csv(stationKeyLoc) %>%
  pull(basin_name_abrv) %>% unique()
  
# Iterate over each basin.  Broadly, this is doing:
#   1) Create html report with graphs of air/subsurface/surface temp sensors at each reach break
#   2) Add more information to the raw csv files including UTC time, basin, and reach break values.
#   3) Save CSV files with appropriate filenames.  For example: tw_air_02.csv is the air tidbit at reach break 
#      (station) 2 in the Tripps Knob West basin.

# Location of report output
reportDir <- here("data_output/QA_Graphs")

# check if output dir exists.  If not, make it.
if (!dir.exists(reportDir)){
  dir.create(reportDir, recursive = TRUE)
}

for(workingBasin in basinNames){  
rmarkdown::render(here("scripts/temperature_qaqc_report.Rmd"),
                  output_file = paste(workingBasin, "-temperature_QA_ADDSEASON_ADDYEAR",".html", sep = ""),
                  output_dir = here("data_output/QA_Graphs"))
}





